services:
  php82-apache:
    build: .
    image: php:8.2-apache
    container_name: drupal10-php82-apache
    restart: always
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "127.0.0.1:45400:80"
    depends_on:
      - mysql80

  php81-websocket:
    build: ./websocket_server
    image: php:8.1-cli
    container_name: drupal10-php81-websocket
    restart: always
    volumes:
      - ./websocket_server:/var/www/html
    working_dir: /var/www/html
    ports:
      - "45401:5609"
    depends_on:
      - mysql80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal10-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql80
      PMA_USER: root
      PMA_PASSWORD: pass123
      PMA_DATABASE: drupaldb
    ports:
      - "45402:80"
    depends_on:
      - mysql80

  adminer:
    image: adminer
    container_name: drupal10-adminer
    restart: always
    environment:
      PMA_HOST: mysql80
      PMA_USER: root
      PMA_PASSWORD: pass123
      PMA_DATABASE: drupaldb
    ports:
      - "45403:8080"
    depends_on:
      - mysql80

  mysql80:
    build: ./mysql
    container_name: drupal10-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: drupaldb
    ports:
      - "33454:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/mysql-init:/docker-entrypoint-initdb.d

volumes:
  src:
  mysql-data:
  mysql-init:
